create table anuncio (
  codigo_anuncio serial primary key,
  descricao varchar(255) not null,
  codigo_casa integer not null,
  codigo_usuario integer not null,
  foreign key (codigo_casa) references casa(codigo_casa),
  foreign key (codigo_usuario) references usuario(codigo)
);

INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque',1,1),('posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget,',2,2),('nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam',3,3),('Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis',4,4),('dui quis accumsan convallis, ante lectus convallis est, vitae sodales',5,5),('dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit',6,6),('vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi',7,7),('placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante,',8,8),('convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt',9,9),('arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.',10,10);
INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis',11,11),('dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis',12,12),('dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit',13,13),('et magnis dis parturient montes, nascetur ridiculus mus. Proin vel',14,14),('tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing,',15,15),('fermentum metus. Aenean sed pede nec ante blandit viverra. Donec',16,16),('sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus',17,17),('justo eu arcu. Morbi sit amet massa. Quisque porttitor eros',18,18),('velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae',19,19),('urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus',20,20);
INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('quis accumsan convallis, ante lectus convallis est, vitae sodales nisi',21,21),('odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a,',22,22),('consequat enim diam vel arcu. Curabitur ut odio vel est',23,23),('tempor lorem, eget mollis lectus pede et risus. Quisque libero',24,24),('sit amet ultricies sem magna nec quam. Curabitur vel lectus.',25,25),('euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas',26,26),('dictum eleifend, nunc risus varius orci, in consequat enim diam',27,27),('auctor, nunc nulla vulputate dui, nec tempus mauris erat eget',28,28),('Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis',29,29),('adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis',30,30);
INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('Ut tincidunt vehicula risus. Nulla eget metus eu erat semper',31,31),('porttitor tellus non magna. Nam ligula elit, pretium et, rutrum',32,32),('tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse',33,33),('eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus',34,34),('fames ac turpis egestas. Fusce aliquet magna a neque. Nullam',35,35),('Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie',36,36),('Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed',37,37),('vitae erat vel pede blandit congue. In scelerisque scelerisque dui.',38,38),('Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo,',39,39),('sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis,',40,40);
INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis',41,41),('augue ac ipsum. Phasellus vitae mauris sit amet lorem semper',42,42),('fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque',43,43),('cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut',44,44),('magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec',45,45),('mi tempor lorem, eget mollis lectus pede et risus. Quisque',46,46),('sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.',47,47),('Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna.',48,48),('pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare',49,49),('Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue',50,50);
INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis',51,51),('ornare sagittis felis. Donec tempor, est ac mattis semper, dui',52,52),('erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla.',53,53),('lacus vestibulum lorem, sit amet ultricies sem magna nec quam.',54,54),('egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie',55,55),('Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id,',56,56),('augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel,',57,57),('amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede,',58,58),('elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum',59,59),('eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec',60,60);
INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris',61,61),('sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam',62,62),('justo sit amet nulla. Donec non justo. Proin non massa',63,63),('arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim.',64,64),('Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros.',65,65),('urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat',66,66),('tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu',67,67),('sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum',68,68),('malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas,',69,69),('eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam',70,70);
INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed',71,71),('arcu. Vestibulum ante ipsum primis in faucibus orci luctus et',72,72),('tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec',73,73),('massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede',74,74),('luctus sit amet, faucibus ut, nulla. Cras eu tellus eu',75,75),('tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec',76,76),('ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id',77,77),('scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu',78,78),('purus gravida sagittis. Duis gravida. Praesent eu nulla at sem',79,79),('et risus. Quisque libero lacus, varius et, euismod et, commodo',80,80);
INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer',81,81),('Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque',82,82),('Ut semper pretium neque. Morbi quis urna. Nunc quis arcu',83,83),('tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel,',84,84),('nisi nibh lacinia orci, consectetuer euismod est arcu ac orci.',85,85),('Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas',86,86),('vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id',87,87),('rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida',88,88),('Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat.',89,89),('tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id,',90,90);
INSERT INTO anuncio (descricao,codigo_casa,codigo_usuario) VALUES ('Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis',91,91),('gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.',92,92),('massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at',93,93),('velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor',94,94),('eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula.',95,95),('dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc',96,96),('Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean',97,97),('massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede',98,98),('ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat.',99,99),('sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus',100,100);